-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "middleName" DROP NOT NULL,
ALTER COLUMN "lastName" SET DEFAULT '',
ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "contact" SET DEFAULT '0000000000';
